
export const list = [
    {
        id : 1,
        imgUrl : "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
        title : "Gaming Headset",
        description : "this headset is do amazing you can hear someone sneeze inside your game, just kidding bro just buy this shit",
        content : "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Numquam nemo velit doloremque ad nam mollitia vero explicabo totam recusandae? Quas molestias, officiis eum voluptate consequuntur animi quos blanditiis nemo. Earum ipsum itaque voluptate explicabo commodi dicta, quaerat vitae eaque non doloribus iste id voluptatem deserunt officiis totam aliquam temporibus unde cupiditate esse rem laboriosam porro labore ipsa? Quidem inventore exercitationem hic culpa corporis veritatis incidunt in enim similique neque ut architecto fugiat, totam commodi illum debitis saepe! Quae corporis laboriosam beatae repellat odio a dolorum quibusdam officiis! Odit labore et repellat corporis laborum, similique assumenda eveniet ratione voluptatibus, ea ab nobis eum. Facere suscipit perspiciatis voluptatibus officiis voluptate tempora. Harum ipsum tenetur natus minus, maiores repellat aliquid similique alias maxime totam atque libero voluptate praesentium, reiciendis neque aperiam tempora accusamus? Doloribus dolores ipsa veritatis eius assumenda corporis itaque minus neque illum expedita fugiat voluptates quibusdam non officia praesentium aliquam eaque facere voluptatibus iusto repellendus labore, pariatur quas error odit. Perferendis, inventore animi! Dicta officiis iste rerum fugiat, atque maiores. Aspernatur doloribus non repellat necessitatibus quia eum hic autem neque, voluptas quam id quas facere blanditiis aperiam, minus excepturi! Eum veritatis quas quia ea nihil eius, enim sed impedit ipsum illo!",
    },
    {
        id : 2,
        imgUrl : "https://www.tremplin-numerique.org/wp-content/uploads/2022/06/Comment-choisir-la-bonne-souris-de-jeu-3173143..jpg",
        title : "Gaming Mouse",
        description : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt autem obcaecati eos nam mollitia vero sint voluptas totam incidunt deleniti.Lorem ipsum",
        content : "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Numquam nemo velit doloremque ad nam mollitia vero explicabo totam recusandae? Quas molestias, officiis eum voluptate consequuntur animi quos blanditiis nemo. Earum ipsum itaque voluptate explicabo commodi dicta, quaerat vitae eaque non doloribus iste id voluptatem deserunt officiis totam aliquam temporibus unde cupiditate esse rem laboriosam porro labore ipsa? Quidem inventore exercitationem hic culpa corporis veritatis incidunt in enim similique neque ut architecto fugiat, totam commodi illum debitis saepe! Quae corporis laboriosam beatae repellat odio a dolorum quibusdam officiis! Odit labore et repellat corporis laborum, similique assumenda eveniet ratione voluptatibus, ea ab nobis eum. Facere suscipit perspiciatis voluptatibus officiis voluptate tempora. Harum ipsum tenetur natus minus, maiores repellat aliquid similique alias maxime totam atque libero voluptate praesentium, reiciendis neque aperiam tempora accusamus? Doloribus dolores ipsa veritatis eius assumenda corporis itaque minus neque illum expedita fugiat voluptates quibusdam non officia praesentium aliquam eaque facere voluptatibus iusto repellendus labore, pariatur quas error odit. Perferendis, inventore animi! Dicta officiis iste rerum fugiat, atque maiores. Aspernatur doloribus non repellat necessitatibus quia eum hic autem neque, voluptas quam id quas facere blanditiis aperiam, minus excepturi! Eum veritatis quas quia ea nihil eius, enim sed impedit ipsum illo!",
    },
    {
        id : 3,
        imgUrl : "https://www.howtogeek.com/wp-content/uploads/2022/04/rgb-lit-gaming-mechanical-keyboard.jpg?height=200p&trim=2,2,2,2",
        title : "Gaming Keyboard",
        description : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt autem obcaecati eos nam mollitia vero sint voluptas totam incidunt deleniti.Lorem ipsum",
        content : "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Numquam nemo velit doloremque ad nam mollitia vero explicabo totam recusandae? Quas molestias, officiis eum voluptate consequuntur animi quos blanditiis nemo. Earum ipsum itaque voluptate explicabo commodi dicta, quaerat vitae eaque non doloribus iste id voluptatem deserunt officiis totam aliquam temporibus unde cupiditate esse rem laboriosam porro labore ipsa? Quidem inventore exercitationem hic culpa corporis veritatis incidunt in enim similique neque ut architecto fugiat, totam commodi illum debitis saepe! Quae corporis laboriosam beatae repellat odio a dolorum quibusdam officiis! Odit labore et repellat corporis laborum, similique assumenda eveniet ratione voluptatibus, ea ab nobis eum. Facere suscipit perspiciatis voluptatibus officiis voluptate tempora. Harum ipsum tenetur natus minus, maiores repellat aliquid similique alias maxime totam atque libero voluptate praesentium, reiciendis neque aperiam tempora accusamus? Doloribus dolores ipsa veritatis eius assumenda corporis itaque minus neque illum expedita fugiat voluptates quibusdam non officia praesentium aliquam eaque facere voluptatibus iusto repellendus labore, pariatur quas error odit. Perferendis, inventore animi! Dicta officiis iste rerum fugiat, atque maiores. Aspernatur doloribus non repellat necessitatibus quia eum hic autem neque, voluptas quam id quas facere blanditiis aperiam, minus excepturi! Eum veritatis quas quia ea nihil eius, enim sed impedit ipsum illo!",
    },
    {
        id : 4,
        imgUrl : "https://m.media-amazon.com/images/I/61NrAZHeuCL.jpg",
        title : "microphone bj233",
        description : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt autem obcaecati eos nam mollitia vero sint voluptas totam incidunt deleniti.Lorem ipsum",
        content : "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Numquam nemo velit doloremque ad nam mollitia vero explicabo totam recusandae? Quas molestias, officiis eum voluptate consequuntur animi quos blanditiis nemo. Earum ipsum itaque voluptate explicabo commodi dicta, quaerat vitae eaque non doloribus iste id voluptatem deserunt officiis totam aliquam temporibus unde cupiditate esse rem laboriosam porro labore ipsa? Quidem inventore exercitationem hic culpa corporis veritatis incidunt in enim similique neque ut architecto fugiat, totam commodi illum debitis saepe! Quae corporis laboriosam beatae repellat odio a dolorum quibusdam officiis! Odit labore et repellat corporis laborum, similique assumenda eveniet ratione voluptatibus, ea ab nobis eum. Facere suscipit perspiciatis voluptatibus officiis voluptate tempora. Harum ipsum tenetur natus minus, maiores repellat aliquid similique alias maxime totam atque libero voluptate praesentium, reiciendis neque aperiam tempora accusamus? Doloribus dolores ipsa veritatis eius assumenda corporis itaque minus neque illum expedita fugiat voluptates quibusdam non officia praesentium aliquam eaque facere voluptatibus iusto repellendus labore, pariatur quas error odit. Perferendis, inventore animi! Dicta officiis iste rerum fugiat, atque maiores. Aspernatur doloribus non repellat necessitatibus quia eum hic autem neque, voluptas quam id quas facere blanditiis aperiam, minus excepturi! Eum veritatis quas quia ea nihil eius, enim sed impedit ipsum illo!",
    },
    {
        id : 5,
        imgUrl : "https://media.wired.com/photos/62d75d34ddaaa99a1df8e61d/master/pass/Phone-Camera-Webcam-Gear-GettyImages-1241495650.jpg",
        title : "Iphone 13",
        description : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt autem obcaecati eos nam mollitia vero sint voluptas totam incidunt deleniti.Lorem ipsum",
        content : "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Numquam nemo velit doloremque ad nam mollitia vero explicabo totam recusandae? Quas molestias, officiis eum voluptate consequuntur animi quos blanditiis nemo. Earum ipsum itaque voluptate explicabo commodi dicta, quaerat vitae eaque non doloribus iste id voluptatem deserunt officiis totam aliquam temporibus unde cupiditate esse rem laboriosam porro labore ipsa? Quidem inventore exercitationem hic culpa corporis veritatis incidunt in enim similique neque ut architecto fugiat, totam commodi illum debitis saepe! Quae corporis laboriosam beatae repellat odio a dolorum quibusdam officiis! Odit labore et repellat corporis laborum, similique assumenda eveniet ratione voluptatibus, ea ab nobis eum. Facere suscipit perspiciatis voluptatibus officiis voluptate tempora. Harum ipsum tenetur natus minus, maiores repellat aliquid similique alias maxime totam atque libero voluptate praesentium, reiciendis neque aperiam tempora accusamus? Doloribus dolores ipsa veritatis eius assumenda corporis itaque minus neque illum expedita fugiat voluptates quibusdam non officia praesentium aliquam eaque facere voluptatibus iusto repellendus labore, pariatur quas error odit. Perferendis, inventore animi! Dicta officiis iste rerum fugiat, atque maiores. Aspernatur doloribus non repellat necessitatibus quia eum hic autem neque, voluptas quam id quas facere blanditiis aperiam, minus excepturi! Eum veritatis quas quia ea nihil eius, enim sed impedit ipsum illo!",
    },
    {
        id : 6,
        imgUrl : "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HPNG2?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1620941467000",
        title : "PS5 controler",
        description : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt autem obcaecati eos nam mollitia vero sint voluptas totam incidunt deleniti.Lorem ipsum",
        content : "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Numquam nemo velit doloremque ad nam mollitia vero explicabo totam recusandae? Quas molestias, officiis eum voluptate consequuntur animi quos blanditiis nemo. Earum ipsum itaque voluptate explicabo commodi dicta, quaerat vitae eaque non doloribus iste id voluptatem deserunt officiis totam aliquam temporibus unde cupiditate esse rem laboriosam porro labore ipsa? Quidem inventore exercitationem hic culpa corporis veritatis incidunt in enim similique neque ut architecto fugiat, totam commodi illum debitis saepe! Quae corporis laboriosam beatae repellat odio a dolorum quibusdam officiis! Odit labore et repellat corporis laborum, similique assumenda eveniet ratione voluptatibus, ea ab nobis eum. Facere suscipit perspiciatis voluptatibus officiis voluptate tempora. Harum ipsum tenetur natus minus, maiores repellat aliquid similique alias maxime totam atque libero voluptate praesentium, reiciendis neque aperiam tempora accusamus? Doloribus dolores ipsa veritatis eius assumenda corporis itaque minus neque illum expedita fugiat voluptates quibusdam non officia praesentium aliquam eaque facere voluptatibus iusto repellendus labore, pariatur quas error odit. Perferendis, inventore animi! Dicta officiis iste rerum fugiat, atque maiores. Aspernatur doloribus non repellat necessitatibus quia eum hic autem neque, voluptas quam id quas facere blanditiis aperiam, minus excepturi! Eum veritatis quas quia ea nihil eius, enim sed impedit ipsum illo!",
    }
]